### ISSUE TITLE
issue with files in static directory when app is built

### ISSUE THREAD

**Issue by creedr** [DylanAllen/noiiice#14]
When I build and deploy the app with `sls deploy --stage prod`, it seems that nothing from the `static` directory is bundled in the `.nuxt` directory. 

For instance I have tried to include my own favicon.ico or even just a my-icon.png in the `static/` directory and when I open the app in the browser it shows a 404 for that file when watching the network monitor. I've noticed this on noiiice.com as well (at least with Firefox) where `noiiice-icon-trans.png` returns a 404.
My `nuxt.config.js` looks like
```
link: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        href: 'favicon.ico'
        // href: 'my-icon.png',
        //href: 'noiiice-icon-trans.png',
      },
```

The browser tab icon or `favicon.ico` works fine when I just run `npm run dev`. 

Also, Chrome is showing `sw.js` has a failed status, so that file is not being included in the `.nuxt` bundle either, although the app seems to work fine without it.

Have you noticed these issues?

**Comment by DylanAllen** [comment]
Good catch. You can include the static folder by adding `- apps/app/static/**` under line 99 in `serverless.yml`. so that the nuxt function looks like this:
```yml
functions:
  nuxt:
    handler: index.nuxt
    package:
      exclude:
        - "**/*"
      include:
        - nuxt.config.js
        - nuxtHandler.js
        - index.js
        - package.json
        - secrets.json
        - binaryMimeTypes.js
        - apps/app/config.js
        - .nuxt/**
        - apps/app/static/**
```
 I will update that in the repo as well. Thanks!
