### ISSUE TITLE
Running from a different region

### ISSUE THREAD

**Issue by CliffS** [DylanAllen/noiiice#6]
Hi

Trying to follow the instructions step by step, while running `sls deploy --stage dev`, I get:

```
  Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayCustomDomain - Invalid certificate ARN: arn:aws:acm:eu-west-1:017316296168:certificate/cf936418-85df-47e8-beb7-338d4751eaad. Certificate must be in 'us-east-1'. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 2bd10173-fb7f-43c3-9b8a-f21f6dbc7cfe).
```

**Comment by DylanAllen** [comment]
Hi CliffS,

On line 569 of the `serverless.yml` file, change `- EDGE` to `- REGIONAL`

```
ApiGatewayCustomDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: ${self:provider.config.certificateArn}
        DomainName: ${self:provider.config.domain}
        EndpointConfiguration:
          Types:
            - REGIONAL
```

I believe EDGE is only supported in us-east-1. Let me know if this works. If so I will make this value dynamic based on the region.

**Comment by CliffS** [comment]
```
  Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayCustomDomain - Cannot import certificates for EDGE while REGIONAL is active. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 2f643dcb-60ba-47a8-93ee-890e7ad00c1e).
```

**Comment by DylanAllen** [comment]
One more change that I missed, change `CertificateArn` to `RegionalCertificateArn` on 565:

```
ApiGatewayCustomDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        RegionalCertificateArn: ${self:provider.config.certificateArn}
        DomainName: ${self:provider.config.domain}
        EndpointConfiguration:
          Types:
            - EDGE
```
